In [1]:
import numpy as np

arr_ = np.array([101, 201, 301, 401, 501])

print(arr_)  # Changed 'array' to 'arr_'

print(type(arr_))  # Changed 'arr' to 'arr_'


[101 201 301 401 501]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

nameList = ['Angel', "Shemi", "Marvel", "Linda"]
ageTuple = (41, 32, 21, 19)
gradeDict = {"CSC102": 89, "MTH 102": 77, "CHM 102": 69, "GST 102": 99}

# Correct variable names and use consistent case
arr_nameList = np.array(nameList)  # Changed 'namelist' to 'nameList'
arr_ageTuple = np.array(ageTuple)  # Changed 'ageTupple' to 'ageTuple'
arr_gradeDict = np.array(list(gradeDict.items()))  # Changed 'gradedDict' to 'gradeDict' and converted dict to list of items

print(arr_nameList)
print(arr_ageTuple)
print(arr_gradeDict)


['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
[['CSC102' '89']
 ['MTH 102' '77']
 ['CHM 102' '69']
 ['GST 102' '99']]


In [3]:
import numpy as np

classNum = int(input("How many students are in the CSC 102 class?"))

# If you're planning to use NumPy for a reason that might not be apparent in this snippet,
# we can create an array, but it's not necessary for just the number count.
class_arr = np.array([classNum])  # Store classNum in an array if needed for further processing

if class_arr[0] == 1:  # Access the first element if using an array
    print("There is only", class_arr[0], "student in the CSC 102 class")
else:
    print("There are", class_arr[0], "students in the CSC 102 class")


How many students are in the CSC 102 class? 7


There are 7 students in the CSC 102 class


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

# Adding the missing closing bracket for the numpy array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import numpy as np

# Change curly braces to parentheses for defining numpy arrays
a = np.array(42)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
# Add the missing closing bracket
d = np.array([1, 2, 3, 4, 5])

print(a.ndim)  # Outputs the number of dimensions of array a
print(b.ndim)  # Outputs the number of dimensions of array b
print(c.ndim)  # Outputs the number of dimensions of array c
print(d.ndim)  # Outputs the number of dimensions of array d


0
3
2
1


In [8]:
import numpy as np

# Correct the function name from np.aray to np.array
arr = np.array([1, 2, 3, 4], ndmin=8)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[[1 2 3 4]]]]]]]]
number of dimensions : 8


In [10]:
import numpy as np

# Remove the extra bracket in the array definition
arr = np.array([1, 2, 3, 4])

# Remove the extra parenthesis in the print statement
print(arr[1])


2


In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Correct the index to access the 5th element on the 2nd row
print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Correctly access the element in the position [0, 1, 2]
print(arr[0, 1, 2])


6


In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Correct the index to -1 to properly access the last element of the second dimension
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [16]:
import numpy as np

# Correct typo from 'nop' to 'np'
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 1 to index 5 (the slice will include index 1 and exclude index 5)
print(arr[1:5])


[2 3 4 5]


In [17]:
import numpy as np

# Use square brackets for slicing instead of parentheses
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 4 to the end of the array
print(arr[4:])


[5 6 7]


In [18]:
import numpy as np

# Use correct syntax for the print function
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from the beginning of the array to index 4, not including index 4
print(arr[:4])


[1 2 3 4]


In [20]:
import numpy as np

int_arr = np.array([1, 2, 3, 4])
str_arr = np.array(['apple', 'banana', 'cherry'])

# Correctly print the data type of the integer array
print(int_arr.dtype)

# Correct the typo from 'dype' to 'dtype' for the string array
print(str_arr.dtype)


int32
<U6


In [22]:
import numpy as np

# Correcting the typo from 'aray' to 'array'
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Iterating through each element of the 2-D array
for x in arr:
    for y in x:
        print(y,x)  # If you also want to print which sub-array 'y' belongs to, you can keep it as `print(y, x)`


1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [23]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# To iterate over every element in a 3-D array
for block in arr:
    for row in block:
        for element in row:
            print(element)


1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
import numpy as np

# Correct the typo from 'aray' to 'array'
arr1 = np.array([1, 2, 3])

# Correct variable name arr2_
arr2 = np.array([4, 5, 6])

# Correct the variable reference in concatenate
arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [25]:
import numpy as np

# Add the missing closing parenthesis for the np.array definition
arr = np.array([1, 2, 3, 4, 5, 6])

# Use np.array_split to split the array into 3 parts
newarr = np.array_split(arr, 3)

# Correct the print statement to use parentheses instead of brackets
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
import numpy as np

# Correct array variable name in array_split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

# Correct print syntax to use parentheses instead of brackets
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [27]:
import numpy as np

# Correct the array to use a list or sub-array instead of a set
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Split the array into 3 parts
newarr = np.array_split(arr, 3)

# Print the resulting arrays from the split
print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
